controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    gripper_controller_l:
      type: position_controllers/GripperActionController

    gripper_controller_r:
      type: position_controllers/GripperActionController


velocity_controller:
  ros__parameters:
    joints:
      - yumi_joint_1_r
      - yumi_joint_2_r
      - yumi_joint_7_r
      - yumi_joint_3_r
      - yumi_joint_4_r
      - yumi_joint_5_r
      - yumi_joint_6_r
      - yumi_joint_1_l
      - yumi_joint_2_l
      - yumi_joint_7_l
      - yumi_joint_3_l
      - yumi_joint_4_l
      - yumi_joint_5_l
      - yumi_joint_6_l
#      - gripper_r_joint
#      - gripper_l_joint

    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity

gripper_controller_r:
  ros__parameters:
    default: true
    joint: gripper_r_joint
    allow_stalling: true

gripper_controller_l:
  ros__parameters:
    default: true
    joint: gripper_l_joint
    allow_stalling: true